# Generated by Django 2.2.5 on 2021-01-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210102_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='loc',
        ),
    ]
